services:
    bot:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: afifa-obedqueue-bot
        command: php artisan telegram:poll
        volumes:
            - .:/var/www
        depends_on:
            - app
        networks:
            - afifa-obedqueue

    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: afifa-obedqueue-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - afifa-obedqueue
    db:
        image: postgres:15
        container_name: afifa-obedqueue-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - afifa-obedqueue

    nginx:
        image: nginx:alpine
        container_name: afifa-obedqueue-nginx
        ports:
            - "89:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - afifa-obedqueue

volumes:
    pgdata:

networks:
    afifa-obedqueue:
